// This file is generated by Slice Machine. Update with care!

import Color from './Color';
import Images from './Images';
import Produto from './Produto';

export { Produto };

export const components = {
  produto: Produto,
};
